[package]
name = "governancer"
version = "0.1.0"
# https://aptos.dev/guides/move-guides/upgrading-move-code/
upgrade_policy = "compatible"

[addresses]
my_addr = "_"
std = "0x1"
aptos_framework = "0x1"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/move-stdlib/", rev="aptos-cli-v1.0.4" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v1.0.4" }
# MoveStdlib = { local = "~/aptos-core/aptos-move/framework/move-stdlib" }
# AptosFramework = { local = "~/aptos-core/aptos-move/framework/aptos-framework" }